Locales['de'] = {
  -- Cloackroom
  ['cloakroom'] = 'Garderobe',
  ['citizen_wear'] = 'Zivilkleidung',
  ['police_wear'] = 'Arbeitskleidung',
  ['gilet_wear'] = 'Refelktierende Jacke',
  ['bullet_wear'] = 'Kugelsichereweste',
  ['no_outfit'] = 'Es gibt keine Uniform die dir passt!',
  ['open_cloackroom'] = 'Drücke ~INPUT_CONTEXT~ um dich umzuziehen',
  -- Armory
  ['remove_object'] = 'Objekt nehmen',
  ['deposit_object'] = 'Objekt ablegen',
  ['get_weapon'] = 'Waffen holen',
  ['put_weapon'] = 'Waffen bringen',
  ['buy_weapons'] = 'Waffen kaufen',
  ['armory'] = 'Waffenkammer',
  ['open_armory'] = 'Drücke ~INPUT_CONTEXT~ um die Waffenkammer zu öffnen',
  ['armory_owned'] = 'owned',
  ['armory_free'] = 'Frei',
  ['armory_item'] = '$%s',
  ['armory_weapontitle'] = 'Waffenkammer - Waffe kaufen',
  ['armory_componenttitle'] = 'Waffenkammer - Waffen zubehör',
  ['armory_bought'] = 'du hast eine ~y~%s~s~ für ~g~$%s~s~ gekauft',
  ['armory_money'] = 'Sie können sich diese Waffe nicht leisten',
  ['armory_hascomponent'] = 'Sie haben das Waffen zubehöt ausgerüstet!',
  ['get_weapon_menu'] = 'Waffenkammer- Waffe rausholen',
  ['put_weapon_menu'] = 'Waffenkammer - Waffe ablegen',
  -- Vehicles
  ['vehicle_menu'] = 'Fahrzeug',
  ['vehicle_blocked'] = 'Alle verfügbaren Spawnpunkte sind derzeit gesperrt!',
  ['garage_prompt'] = 'Drücken sie ~INPUT_CONTEXT~ um auf die ~y~Fahrzeugaktion s~s~ zuzgreifen.',
  ['garage_title'] = 'Fahrzeug Aktion',
  ['garage_stored'] = 'Garage',
  ['garage_notstored'] = 'nicht in der Garage',
  ['garage_storing'] = 'Wir versuchen das Fahrzeug zu entfernen,Stellen sie sicher das sich keine Spieler in der nähe befinden.',
  ['garage_has_stored'] = 'Das Fahrzeug wurde in die Garage geparkt',
  ['garage_has_notstored'] = 'Es wurde kein Fahrzeug in der nähe gefunden',
  ['garage_notavailable'] = 'your vehicle is not stored in the garage.',
  ['garage_blocked'] = 'there\'s no available spawn points!',
  ['garage_empty'] = 'you dont have any vehicles in your garage.',
  ['garage_released'] = 'your vehicle has been released from the garage.',
  ['garage_store_nearby'] = 'there is no nearby vehicles.',
  ['garage_storeditem'] = 'open garage',
  ['garage_storeitem'] = 'store vehicle in garage',
  ['garage_buyitem'] = 'vehicle shop',
  ['garage_notauthorized'] = 'you\'re not authorized to buy this kind of vehicles.',
  ['helicopter_prompt'] = 'press ~INPUT_CONTEXT~ to access the ~y~Helicopter Actions~s~.',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'vehicle Shop',
  ['vehicleshop_confirm'] = 'do you want to buy this vehicle?',
  ['vehicleshop_bought'] = 'you have bought ~y~%s~s~ for ~r~$%s~s~',
  ['vehicleshop_money'] = 'you cannot afford that vehicle',
  ['vehicleshop_awaiting_model'] = 'the vehicle is currently ~g~DOWNLOADING & LOADING~s~ please wait',
  ['confirm_no'] = 'no',
  ['confirm_yes'] = 'yes',
  -- Service
  ['service_max'] = 'you cannot enter service, max officers in service: %s/%s',
  ['service_not'] = 'you have not entered service! You\'ll have to get changed first.',
  ['service_anonunce'] = 'service information',
  ['service_in'] = 'you\'ve entered service, welcome!',
  ['service_in_announce'] = 'operator ~y~%s~s~ has entered service!',
  ['service_out'] = 'you have left service.',
  ['service_out_announce'] = 'operator ~y~%s~s~ has left their service.',
  -- Action Menu
  ['citizen_interaction'] = 'Zivilistenaktionen',
  ['vehicle_interaction'] = 'Fahrzeuginteraktionen',
  ['object_spawner'] = 'Objekt Spawner',

  ['id_card'] = 'ID Karte',
  ['search'] = 'Suche',
  ['handcuff'] = 'Festnehmen / Freilassen',
  ['drag'] = 'ziehen',
  ['put_in_vehicle'] = 'In Fahrzeug setzen',
  ['out_the_vehicle'] = 'aus dem Fahrzeug ziehen',
  ['fine'] = 'Strafe',
  ['unpaid_bills'] = 'unbezahlte Rechungen verwalten',
  ['license_check'] = 'Lizenzen verwalten',
  ['license_revoke'] = 'Lizenzen wiederrufen',
  ['license_revoked'] = 'Ihr ~b~%s~s~ wurde ~y~wiederrufen~s~!',
  ['licence_you_revoked'] = 'Sie haben ein ~b~%s~s~ wiederrufen, das zu ~y~%s~s~ gehörte',
  ['no_players_nearby'] = 'keine Spieler in der Nähe',
  ['being_searched'] = 'Sie werden von der Polizei durchsucht',
  -- Vehicle interaction
  ['vehicle_info'] = 'Fahrzeug Info',
  ['pick_lock'] = 'Fahrzeug öffnen',
  ['vehicle_unlocked'] = 'Fahrzeug ~g~offen~s~',
  ['no_vehicles_nearby'] = 'Keine Fahrzeuge in der Nähe',
  ['impound'] = 'Beschlagnahmtes Fahrzeug',
  ['impound_prompt'] = 'Drücken sie ~INPUT_CONTEXT~ um die ~y~Beschlagnahmung~s~ abzubrechen',
  ['impound_canceled'] = 'Sie haben das beschlagnahmen abgebrochen',
  ['impound_canceled_moved'] = 'Die beschlagnahmung wurde abgebrochen, weil das Fahrzeug bewegt wurde',
  ['impound_successful'] = 'Sie haben das Fahrzeug beschlagnahmt',
  ['search_database'] = 'Fahrzeug Informationen',
  ['search_database_title'] = 'Fahrzeug informationen - Wird über das Kennzeichen gesucht',
  ['search_database_error_invalid'] = 'das ist ~r~nicht~s~a~y~ die gültige~s~ Regestrierungsnummer',
  -- Traffic interaction
  ['traffic_interaction'] = 'Straßeninteraktionen',
  ['cone'] = 'Hütchen',
  ['barrier'] = 'Barriere',
  ['spikestrips'] = 'Nagelband',
  ['box'] = 'Box',
  ['cash'] = 'Box mit Geld',
  -- ID Card Menu
  ['name'] = 'Name: %s',
  ['job'] = 'job: %s',
  ['sex'] = 'sex: %s',
  ['dob'] = 'DOB: %s',
  ['height'] = 'Höhe: %s',
  ['bac'] = 'BAC: %s',
  ['unknown'] = 'Unbekannt',
  ['male'] = 'Mänlich',
  ['female'] = 'Weiblich',
  -- Body Search Menu
  ['guns_label'] = '--- Waffen ---',
  ['inventory_label'] = '--- Inventar ---',
  ['license_label'] = ' --- Lizenzen ---',
  ['confiscate'] = 'konfeszieren %s',
  ['confiscate_weapon'] = 'Konfisziere %s mit %s Kugeln',
  ['confiscate_inv'] = 'konfeziere %sx %s',
  ['confiscate_dirty'] = 'schwarzgeld konfesziert: <span style="color:red;">$%s</span>',
  ['you_confiscated'] = 'Sie haben ~y~%sx~s~ ~b~%s~s~ von ~b~%s~s~ beschlagnahmt',
  ['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ wurde von ~y~%s~s~ beschlagnahmt',
  ['you_confiscated_account'] = 'Sie haben ~g~$%s~s~ (%s) von ~b~%s~s~ beschlagnahmt',
  ['got_confiscated_account'] = '~g~$%s~s~ (%s) wurde von ~y~%s~s~ beschlagnahmt',
  ['you_confiscated_weapon'] = 'Sie haben ~b~%s~s~ mit ~b~%s~s~ von ~o~%s~s~ beschlagnahmt',
  ['got_confiscated_weapon'] = 'Ihre ~b~%s~s~ mit ~o~%s~s~ wurden von ~y~%s~s~ beschlagnahmt',
  ['traffic_offense'] = 'Verkehrs vergehen',
  ['minor_offense'] = 'Geringes vergehen',
  ['average_offense'] = 'Normales vergehen',
  ['major_offense'] = 'Hohes vergehen',
  ['fine_total'] = 'strafe: %s',
  -- Vehicle Info Menu
  ['plate'] = 'plate: %s',
  ['owner_unknown'] = 'besitzer: Unbekannt',
  ['owner'] = 'besitzer: %s',
  -- Boss Menu
  ['open_bossmenu'] = 'Drücke ~INPUT_CONTEXT~ um das Menü zu öffnen',
  ['quantity_invalid'] = 'ungültige Menge',
  ['have_withdrawn'] = 'Sie haben ~y~%sx~s~ ~b~%s~s~genommen',
  ['have_deposited'] = 'Sie haben ~y~%sx~s~ ~b~%s~s~ abgelegt',
  ['quantity'] = 'Menge',
  ['inventory'] = 'inventar',
  ['police_stock'] = 'Polizei Stock',
  -- Misc
  ['remove_prop'] = 'Drücke ~INPUT_CONTEXT~ um das Objekt zu entfernen',
  ['map_blip'] = 'LSPD',
  ['unrestrained_timer'] = 'Sie spüren wie ihre handschellen locker werden und können sich befreien.',
  -- Notifications
  ['alert_police'] = 'Polizei alamieren',
  ['phone_police'] = 'Polizei',
}
