Locales['en'] = {
  -- Cloakroom
  ['cloakroom'] = 'Umkleideraum',
  ['ems_clothes_civil'] = 'Zievilkleider',
  ['ems_clothes_ems'] = 'EMS Kleider',
  -- Vehicles
  ['ambulance'] = 'Krankenwagen',
  ['helicopter_prompt'] = 'Drücken sie ~ INPUT_CONTEXT um auf die ~ y ~ Hubschrauberaktionen ~ s ~ zuzugreifen ~ .',
  ['garage_prompt'] = 'Drücken Sie ~ INPUT_CONTEXT ~, um auf die ~ y ~ Fahrzeugaktionen ~ s ~ zuzugreifen.',
  ['garage_title'] = 'Fahrzeugaktionen',
  ['garage_stored'] = 'Garaga',
  ['garage_notstored'] = 'nicht in der garage',
  ['garage_storing'] = 'Wir versuchen , das Fahrzeug zu entfernen. Stellen Sie sicher das sich keine Spieler in der Nähe befinden.',
  ['garage_has_stored'] = 'Dein Fahrzeug wurde in Ihre Garage geparkt',
  ['garage_has_notstored'] = 'Es wurde keine Fahrzeug in ihrer Nähe gefunden',
  ['garage_notavailable'] = 'Ihr Fahrzeug ist nicht in der Garage geparkt.',
  ['garage_blocked'] = 'Der Spawnpunkt in blockiert!',
  ['garage_empty'] = 'Sie haben keine Fahrzeuge in ihrer Garage.',
  ['garage_released'] = 'Ihr Fahrzeug wurde aus der Garage geparkt.',
  ['garage_store_nearby'] = 'Es gibt keine Fahrzeuge in der Nähe.',
  ['garage_storeditem'] = 'öffne Garage',
  ['garage_storeitem'] = 'Fahrzeug in die Garage geparkt',
  ['garage_buyitem'] = 'Fahrzeugladen',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'Fahrzeugladen',
  ['vehicleshop_confirm'] = 'Möchten sie dieses Auto kaufen?',
  ['vehicleshop_bought'] = 'Sie haben ~y~%s~s~ für~g~$%s~s~ gekauft',
  ['vehicleshop_money'] = 'Sie können sich das Fahrzeug nicht leisten',
  ['vehicleshop_awaiting_model'] = 'Dein Fahrzeug befindent ~g~ Herunterladen & Laden ~s~ Bitte Warten',
  ['confirm_no'] = 'Nein',
  ['confirm_yes'] = 'Ja',
  -- Action Menu
  ['revive_inprogress'] = 'Eine Wiederbelebung ist im Ganga!',
  ['revive_complete'] = 'Sie haben ~y~%s~s~ Wiederbelebt',
  ['revive_complete_award'] = 'Sie haben ~y~%s~s~ Wiederbelbt und verdienen ~g~$%s~s~!',
  ['revive_fail_offline'] = 'Dieser Spieler ist nicht länger auf der Insel',
  ['heal_inprogress'] = 'Du Heilst!',
  ['heal_complete'] = 'Sie haben ~y~%s~s~ geheilt',
  ['no_players'] = 'Keine Spieler in der Nähe',
  ['player_not_unconscious'] = 'Der Bürger ist nicht bewusstlos!',
  ['player_not_conscious'] = 'Der Bürger ist nicht bei beusstsein!',
  -- Boss Menu
  ['boss_actions'] = 'Chef Action',
  -- Misc
  ['invalid_amount'] = '~r~ Ungültiger Betrag',
  ['actions_prompt'] = 'Drücken sie ~INPUT_CONTEXT~ um auf die ~y~Ambulance Actions~s~ zuzugreifen.',
  ['deposit_amount'] = 'Einzahlungsbetrag',
  ['money_withdraw'] = 'Betrag abgezogen',
  ['fast_travel'] = 'Drücken sie  ~INPUT_CONTEXT~ um schnell zu reisen.',
  ['open_pharmacy'] = 'Drücken sie ~INPUT_CONTEXT~ um die Apotheke zu öffnen.',
  ['pharmacy_menu_title'] = 'Apotehke',
  ['pharmacy_take'] = 'Nehmen sie <span style="color:blue;">%s</span>',
  ['medikit'] = 'Verbandskasten',
  ['bandage'] = 'Verband',
  ['max_item'] = 'Du trägst schon genug.',
  -- F6 Menu
  ['ems_menu'] = 'EMS Menü',
  ['ems_menu_title'] = 'Krankenwagen - EMS Menu',
  ['ems_menu_revive'] = 'Bürger wiederbeleben',
  ['ems_menu_putincar'] = 'ins Fahrzeug setzen',
  ['ems_menu_small'] = 'Kleine Wunden versorgen',
  ['ems_menu_big'] = 'Schwere Verletzungen behandeln',
  -- Phone
  ['alert_ambulance'] = 'Alarm Ambulance',
  -- Death
  ['respawn_available_in'] = 'Respawn verfügbar in ~b~%s Minuten %s Sekunden~s~',
  ['respawn_bleedout_in'] = 'Sie werden in ~b~%s Minuten %s Sekunden ~s~\n ausbluten',
  ['respawn_bleedout_prompt'] = 'Halten sie [~b~E~s~] gedrück, um wieder zu erscheinen',
  ['respawn_bleedout_fine'] = 'Halten sie [~b~E~s~] zum respawnen ~g~$%s~s~',
  ['respawn_bleedout_fine_msg'] = 'Du hast ~r~$%s~s~ bezahlt um wieder zu erscheinen.',
  ['distress_send'] = 'Drücken sie [~b~G~s~] um ein Notsignal zu senden',
  ['distress_sent'] = 'Ein Notsignal wurde an das EMS gesendet!',
  ['combatlog_message'] = 'you have been force-respawned because you\'ve previously left the server when dead.',
  -- Revive
  ['revive_help'] = 'Sie haben einen Spieler wiederbelebt',
  -- Item
  ['used_medikit'] = 'Sie haben ein ~y~1x~s~ Verbandskasten',
  ['used_bandage'] = 'Sie haben eine ~y~1x~s~ Verbend',
  ['not_enough_medikit'] = 'Du hast kein ~b~Verbandskasten~s~.',
  ['not_enough_bandage'] = 'Du hast kein Verband ~b~Verband~s~.',
  ['healed'] = 'Du wurdest behandelt.',
  -- Blips
  ['blip_hospital'] = 'Karankenhaus',
  ['blip_dead'] = 'Bewustloser Bürger',
}
